"""Code templates: render pipeline.py / dag.py / mapping.yaml from an IngestionPlan.

The rendered code is what the harness executes in a sandbox and what a reviewer opens
first, so it is plain, commented, standard-library-only Python (LLD section 3). The same
module also hosts ``inject_defect``, which turns clean output into one of the six frozen
corpus defects (LLD section 2.2) by a targeted, plausible edit.
"""

from __future__ import annotations

import json
import re
from string import Template
from typing import Any

import yaml
from pydantic import BaseModel, ConfigDict, ValidationError

from drydock.models import CANONICAL_COLUMNS, ColumnSpec, IngestionPlan, SourceFormat
from drydock.providers import ProviderError

DEFECT_IDS: frozenset[str] = frozenset(
    {
        "date_format_swapped",
        "trailer_not_skipped",
        "wrong_slice",
        "amount_sign_dropped",
        "thousands_separator_kept",
        "dag_missing_dependency",
    }
)

FILE_EXTENSION: dict[SourceFormat, str] = {
    SourceFormat.CSV: "csv",
    SourceFormat.FIXED_WIDTH: "txt",
    SourceFormat.JSON_LINES: "jsonl",
}

_THOUSANDS_MARKER = 'cleaned.replace(",", "")'
MAX_LINE_LENGTH = 100  # generated code follows the repository's ruff line length


class ParseOptions(BaseModel):
    """Typed view of ``IngestionPlan.parse_options`` with the LLD defaults."""

    model_config = ConfigDict(frozen=True, extra="ignore")

    delimiter: str = ","
    encoding: str = "utf-8"
    header_rows: int = 1
    trailer_rows: int = 0
    skip_blank_lines: bool = True


def parse_options(plan: IngestionPlan) -> ParseOptions:
    try:
        return ParseOptions.model_validate(plan.parse_options)
    except ValidationError as exc:
        raise ProviderError(f"plan.parse_options is invalid: {exc}") from exc


def _py(value: Any) -> str:
    """Render a Python literal for a str / int / bool / None value."""
    if value is None:
        return "None"
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, int):
        return str(value)
    return json.dumps(str(value))


# --------------------------------------------------------------------------- #
# pipeline.py                                                                  #
# --------------------------------------------------------------------------- #

_PIPELINE_HEAD = Template('''"""Ingestion pipeline for ${client} / ${feed_name} (${format_label}).

Generated by DRYDOCK from the client feed contract. Standard library only: no third-party
imports, no network access, no file writes. dag.py wires extract -> transform -> load; the
DRYDOCK harness imports this module and calls extract() and transform() directly.

Canonical output, one dict per row with keys in this order:
    trade_id, account_id, value_date (YYYY-MM-DD), amount (signed, two decimals, no
    thousands separator), currency (ISO-4217 upper-case), counterparty, description
"""

${format_import}from dataclasses import dataclass
from datetime import datetime
from decimal import ROUND_HALF_UP, Decimal

# --------------------------------------------------------------------------- #
# Feed parameters (from the feed contract)                                     #
# --------------------------------------------------------------------------- #

SOURCE_FORMAT = ${source_format}
DELIMITER = ${delimiter}
ENCODING = ${encoding}
HEADER_ROWS = ${header_rows}  # leading lines to skip; the last one names the columns
TRAILER_ROWS = ${trailer_rows}  # trailing lines to skip (totals / record-count footer)
SKIP_BLANK_LINES = ${skip_blank_lines}

CANONICAL_COLUMNS = (
${canonical_columns}
)


@dataclass(frozen=True)
class Column:
    """How one source field becomes one canonical field.

    source:          CSV header name, JSON key, or fixed-width slice "start:end".
    target:          canonical column, or None when the source field is dropped.
    dtype:           "str" | "date" | "decimal" | "int".
    date_format:     strptime pattern for dtype="date".
    sign_column:     source field whose value decides the sign of a decimal field.
    negative_marker: value of sign_column that makes the amount negative (e.g. "DR").
    default:         value used when the source field is empty or missing.
    """

    source: str
    target: str | None = None
    dtype: str = "str"
    date_format: str | None = None
    sign_column: str | None = None
    negative_marker: str | None = None
    default: str | None = None


COLUMN_MAP = (
${column_map}
)


# --------------------------------------------------------------------------- #
# Extract                                                                      #
# --------------------------------------------------------------------------- #


def _read_lines(path):
    """Return (header_lines, data_lines) after dropping blanks and the trailer.

    Header and trailer counts refer to non-blank lines when SKIP_BLANK_LINES is set,
    which is how feed contracts normally count them.
    """
    with open(path, encoding=ENCODING, newline="") as handle:
        lines = handle.read().splitlines()
    if SKIP_BLANK_LINES:
        lines = [line for line in lines if line.strip()]
    header_lines = lines[:HEADER_ROWS]
    body = lines[HEADER_ROWS:]
    if TRAILER_ROWS > 0:
        body = body[:-TRAILER_ROWS]
    return header_lines, body
''')

_EXTRACT_CSV = '''

def extract(path):
    """Read the delimited file and return one dict per data row, keyed by header name.

    The last header line supplies the column names; when the feed has no header the
    contract's source names are applied positionally. Short records are padded with ""
    so every row carries every column.
    """
    header_lines, body = _read_lines(path)
    if header_lines:
        header = next(csv.reader([header_lines[-1]], delimiter=DELIMITER))
        names = [name.strip() for name in header]
    else:
        names = [column.source for column in COLUMN_MAP]
    rows = []
    for record in csv.reader(body, delimiter=DELIMITER):
        padded = record + [""] * (len(names) - len(record))
        rows.append({name: value.strip() for name, value in zip(names, padded, strict=False)})
    return rows
'''

_EXTRACT_FIXED_WIDTH = '''

def _parse_slice(spec):
    """Turn a layout slice such as "12:20" into (start, end) character offsets."""
    start, end = spec.split(":")
    return int(start), int(end)


def extract(path):
    """Cut each fixed-width record into fields, keyed by their "start:end" slice.

    Every slice named in COLUMN_MAP (sign columns included) is sliced from the line and
    stripped of padding, so transform() addresses fields by slice like any other key.
    """
    _, body = _read_lines(path)
    slices = {}
    for column in COLUMN_MAP:
        slices[column.source] = _parse_slice(column.source)
        if column.sign_column is not None:
            slices[column.sign_column] = _parse_slice(column.sign_column)
    rows = []
    for line in body:
        rows.append({key: line[start:end].strip() for key, (start, end) in slices.items()})
    return rows
'''

_EXTRACT_JSONL = '''

def _as_text(value):
    """JSON scalars become strings; null becomes "" so downstream rules see one type."""
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def extract(path):
    """Parse one JSON object per line into a dict of string values."""
    _, body = _read_lines(path)
    rows = []
    for line in body:
        record = json.loads(line)
        rows.append({str(key): _as_text(value) for key, value in record.items()})
    return rows
'''

_PIPELINE_TAIL = '''

# --------------------------------------------------------------------------- #
# Transform                                                                    #
# --------------------------------------------------------------------------- #


def transform(rows):
    """Map raw source rows onto the canonical schema, one output dict per input row."""
    return [_transform_row(row) for row in rows]


def _transform_row(row):
    # Start from the full canonical shape so key order is fixed and unmapped columns are "".
    out = {name: "" for name in CANONICAL_COLUMNS}
    for column in COLUMN_MAP:
        if column.target is None:
            continue  # dropped: present in the source, absent from the canonical schema
        raw = row.get(column.source, "").strip()
        if raw == "" and column.default is not None:
            raw = column.default
        out[column.target] = _convert(raw, column, row)
    return out


def _convert(raw, column, row):
    """Apply the dtype rule for one field; every canonical value is a string."""
    if column.dtype == "date":
        return _to_iso_date(raw, column.date_format)
    if column.dtype == "decimal":
        amount = _to_decimal(raw)
        if column.sign_column is not None:
            marker = row.get(column.sign_column, "")
            amount = _apply_sign(amount, marker, column.negative_marker)
        return _format_amount(amount)
    if column.dtype == "int":
        return str(int(_to_decimal(raw))) if raw else ""
    if column.target == "currency":
        return raw.upper()  # ISO-4217 codes are upper-case
    return raw


def _to_iso_date(text, date_format):
    """Re-format a source date such as "03/09/2026" to ISO-8601 (2026-09-03)."""
    if not text:
        return ""
    return datetime.strptime(text, date_format or "%Y-%m-%d").date().isoformat()


def _to_decimal(text):
    """Parse a source amount such as "1,234.50" or "(12.00)" into a Decimal."""
    cleaned = text.strip()
    cleaned = cleaned.replace(",", "")  # drop thousands separators: "1,234.50" -> "1234.50"
    if cleaned.startswith("(") and cleaned.endswith(")"):
        cleaned = "-" + cleaned[1:-1]  # accounting-style negative
    if cleaned in ("", "-"):
        return Decimal("0")
    return Decimal(cleaned)


def _apply_sign(amount, marker, negative_marker):
    """Use the DR/CR style marker to decide the sign of an unsigned source amount."""
    if negative_marker is not None and marker.strip().upper() == negative_marker.upper():
        return -abs(amount)
    return abs(amount)


def _format_amount(amount):
    """Render an amount as a signed string with exactly two decimals ("-1523.40")."""
    quantized = amount.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
    if quantized == 0:
        quantized = abs(quantized)  # normalise "-0.00" to "0.00"
    return f"{quantized:f}"


# --------------------------------------------------------------------------- #
# Load                                                                         #
# --------------------------------------------------------------------------- #


def load(rows):
    """Hand the canonical rows to the downstream sink and return the row count.

    In this reference deployment the rows travel by Airflow XCom (the operator pushes
    the return value); a production deployment swaps in the warehouse writer here.
    The DRYDOCK harness never calls load().
    """
    return len(rows)
'''

_FORMAT_IMPORT: dict[SourceFormat, str] = {
    SourceFormat.CSV: "import csv\n",
    SourceFormat.FIXED_WIDTH: "",
    SourceFormat.JSON_LINES: "import json\n",
}

_EXTRACT_BY_FORMAT: dict[SourceFormat, str] = {
    SourceFormat.CSV: _EXTRACT_CSV,
    SourceFormat.FIXED_WIDTH: _EXTRACT_FIXED_WIDTH,
    SourceFormat.JSON_LINES: _EXTRACT_JSONL,
}

_OPTIONAL_COLUMN_FIELDS = ("dtype", "date_format", "sign_column", "negative_marker", "default")


def _render_column(column: ColumnSpec) -> str:
    """One ``Column(...)`` entry; only non-default keyword arguments are written."""
    parts = [f"source={_py(column.source)}", f"target={_py(column.target)}"]
    for field in _OPTIONAL_COLUMN_FIELDS:
        value = getattr(column, field)
        if value is not None and value != "str":
            parts.append(f"{field}={_py(value)}")
    suffix = "  # dropped" if column.target is None else ""
    one_line = f"    Column({', '.join(parts)}),{suffix}"
    if len(one_line) <= MAX_LINE_LENGTH:
        return one_line
    body = "\n".join(f"        {part}," for part in parts)
    return f"    Column(\n{body}\n    ),{suffix}"


def render_pipeline(plan: IngestionPlan) -> str:
    """Render pipeline.py for the plan's source format (LLD section 3 contract)."""
    options = parse_options(plan)
    head = _PIPELINE_HEAD.substitute(
        client=plan.client,
        feed_name=plan.feed_name,
        format_label=plan.format.value.replace("_", "-"),
        source_format=_py(plan.format.value),
        format_import=_FORMAT_IMPORT[plan.format],
        delimiter=_py(options.delimiter),
        encoding=_py(options.encoding),
        header_rows=options.header_rows,
        trailer_rows=options.trailer_rows,
        skip_blank_lines=_py(options.skip_blank_lines),
        canonical_columns="\n".join(f"    {_py(name)}," for name in CANONICAL_COLUMNS),
        column_map="\n".join(_render_column(column) for column in plan.column_map),
    )
    return head + _EXTRACT_BY_FORMAT[plan.format] + _PIPELINE_TAIL


# --------------------------------------------------------------------------- #
# dag.py                                                                       #
# --------------------------------------------------------------------------- #

_DAG_TEMPLATE = Template(
    '''"""Airflow DAG for ${client} / ${feed_name}: extract -> transform -> load.

Generated by DRYDOCK. Imports are limited to the Airflow DAG and PythonOperator classes,
datetime and the sibling pipeline module. Rows move between tasks through XCom.
"""

from datetime import datetime

from airflow import DAG
from airflow.operators.python import PythonOperator

import pipeline

# Airflow renders {{ ds }} to the logical date, so each run reads that day's drop.
SOURCE_PATH = ${source_path}


def _extract(path):
    """Task 1: read the raw feed; the rows travel to the next task via XCom."""
    return pipeline.extract(path)


def _transform(ti):
    """Task 2: map raw rows onto the canonical schema."""
    rows = ti.xcom_pull(task_ids=${extract_id})
    return pipeline.transform(rows)


def _load(ti):
    """Task 3: hand canonical rows to the sink."""
    rows = ti.xcom_pull(task_ids=${transform_id})
    return pipeline.load(rows)


with DAG(
    dag_id=${dag_id},
    schedule=${schedule},
    start_date=datetime(2026, 1, 1),
    catchup=False,
) as dag:
    extract = PythonOperator(
        task_id=${extract_id},
        python_callable=_extract,
        op_kwargs={"path": SOURCE_PATH},
    )
    transform = PythonOperator(task_id=${transform_id}, python_callable=_transform)
    load = PythonOperator(task_id=${load_id}, python_callable=_load)

    extract >> transform >> load
'''
)


def render_dag(plan: IngestionPlan) -> str:
    """Render dag.py: three PythonOperators chained extract >> transform >> load."""
    if len(plan.task_ids) != 3:
        raise ProviderError(f"plan.task_ids must name exactly three tasks, got {plan.task_ids}")
    extract_id, transform_id, load_id = plan.task_ids
    extension = FILE_EXTENSION[plan.format]
    source_path = f"/data/inbound/{plan.client}/{plan.feed_name}/{{{{ ds }}}}.{extension}"
    return _DAG_TEMPLATE.substitute(
        client=plan.client,
        feed_name=plan.feed_name,
        source_path=_py(source_path),
        dag_id=_py(f"{plan.client}__{plan.feed_name}"),
        schedule=_py(plan.schedule_cron),
        extract_id=_py(extract_id),
        transform_id=_py(transform_id),
        load_id=_py(load_id),
    )


# --------------------------------------------------------------------------- #
# mapping.yaml                                                                 #
# --------------------------------------------------------------------------- #


def _describe_transform(column: ColumnSpec) -> str | None:
    """Human-readable transform note for the mapping document, or None when it is a copy."""
    steps: list[str] = []
    if column.dtype == "date":
        steps.append(f"strptime({column.date_format or '%Y-%m-%d'!r}) -> YYYY-MM-DD")
    if column.dtype == "decimal":
        steps.append("strip thousands separator; Decimal quantized to 2 dp")
        if column.sign_column:
            steps.append(f"negative when {column.sign_column} == {column.negative_marker!r}")
    if column.dtype == "int":
        steps.append("int()")
    if column.target == "currency":
        steps.append("upper()")
    if column.default is not None:
        steps.append(f"default {column.default!r} when empty")
    return "; ".join(steps) or None


def render_mapping(plan: IngestionPlan) -> str:
    """Render the Harbormaster-compatible mapping.yaml (client, feed, format, fields)."""
    fields: list[dict[str, Any]] = []
    for column in plan.column_map:
        field: dict[str, Any] = {
            "source": column.source,
            "target": column.target,
            "dtype": column.dtype,
        }
        note = _describe_transform(column)
        if note is not None:
            field["transform"] = note
        fields.append(field)
    document = {
        "client": plan.client,
        "feed": plan.feed_name,
        "format": plan.format.value,
        "fields": fields,
    }
    return str(yaml.safe_dump(document, sort_keys=False, allow_unicode=True))


def render_all(plan: IngestionPlan) -> tuple[str, str, str]:
    """Convenience: (pipeline_py, dag_py, mapping_yaml) for one plan."""
    return render_pipeline(plan), render_dag(plan), render_mapping(plan)


# --------------------------------------------------------------------------- #
# Defect injection (LLD section 2.2)                                           #
# --------------------------------------------------------------------------- #


def _swap_day_month(fmt: str) -> str:
    """Swap %d and %m ("%d/%m/%Y" <-> "%m/%d/%Y"): the classic transatlantic date bug."""
    return fmt.replace("%d", "\x00").replace("%m", "%d").replace("\x00", "%m")


def _defect_date_format_swapped(pipeline_py: str) -> str:
    match = re.search(r'date_format="([^"]*)"', pipeline_py)
    if match is None or not ("%d" in match.group(1) or "%m" in match.group(1)):
        return pipeline_py
    swapped = _swap_day_month(match.group(1))
    return pipeline_py[: match.start(1)] + swapped + pipeline_py[match.end(1) :]


def _defect_trailer_not_skipped(pipeline_py: str) -> str:
    # Reads as "nobody noticed the totals footer": the trailer count is simply zero.
    pattern = r"^TRAILER_ROWS = [1-9]\d*"
    return re.sub(pattern, "TRAILER_ROWS = 0", pipeline_py, count=1, flags=re.M)


def _defect_wrong_slice(pipeline_py: str) -> str:
    # Off-by-one in the layout: the currency slice starts one character too early, so the
    # last digit of the amount bleeds into the currency code ("0US" instead of "USD").
    match = re.search(r'source="(\d+):(\d+)", target="currency"', pipeline_py) or re.search(
        r'source="(\d+):(\d+)"', pipeline_py
    )
    if match is None:
        return pipeline_py
    start, end = int(match.group(1)) - 1, int(match.group(2)) - 1
    suffix = ', target="currency"' if 'target="currency"' in match.group(0) else ""
    shifted = f'source="{start}:{end}"{suffix}'
    return pipeline_py[: match.start()] + shifted + pipeline_py[match.end() :]


def _defect_amount_sign_dropped(pipeline_py: str) -> str:
    # The DR/CR flag is mapped but never consulted, so every amount comes out positive.
    return re.sub(r'sign_column="[^"]*"', "sign_column=None", pipeline_py, count=1)


def _defect_thousands_separator_kept(pipeline_py: str) -> str:
    # The separator-stripping line is missing, so "1,234.50" reaches Decimal() as-is.
    lines = pipeline_py.split("\n")
    kept = [line for line in lines if _THOUSANDS_MARKER not in line]
    return "\n".join(kept) if len(kept) == len(lines) - 1 else pipeline_py


def _defect_dag_missing_dependency(dag_py: str) -> str:
    # The DAG author chained the first two tasks and forgot the third.
    pattern = r"^([ \t]*)(\w+) >> (\w+) >> (\w+)[ \t]*$"
    return re.sub(pattern, r"\1\2 >> \3", dag_py, count=1, flags=re.M)


_PIPELINE_DEFECTS = {
    "date_format_swapped": _defect_date_format_swapped,
    "trailer_not_skipped": _defect_trailer_not_skipped,
    "wrong_slice": _defect_wrong_slice,
    "amount_sign_dropped": _defect_amount_sign_dropped,
    "thousands_separator_kept": _defect_thousands_separator_kept,
}


def inject_defect(pipeline_py: str, dag_py: str, defect_id: str) -> tuple[str, str]:
    """Apply one frozen defect id to rendered code; returns new (pipeline_py, dag_py).

    Raises ``ProviderError`` for an unknown id, or when the artifact has nothing the defect
    could plausibly break (e.g. ``wrong_slice`` on a CSV feed) so scenarios never pass by
    accident.
    """
    if defect_id not in DEFECT_IDS:
        raise ProviderError(f"unknown defect id '{defect_id}'; known: {sorted(DEFECT_IDS)}")
    if defect_id == "dag_missing_dependency":
        new_dag = _defect_dag_missing_dependency(dag_py)
        if new_dag == dag_py:
            raise ProviderError("defect 'dag_missing_dependency' is not applicable: no chain")
        return pipeline_py, new_dag
    new_pipeline = _PIPELINE_DEFECTS[defect_id](pipeline_py)
    if new_pipeline == pipeline_py:
        raise ProviderError(f"defect '{defect_id}' is not applicable to this pipeline")
    return new_pipeline, dag_py
